[package]
name = "ringbuf"
version = "0.1.0"
authors = ["SF <soporte@supportfactory.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
